cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_js/<int:product_id>/', views.cart_add_js, name='cart_add_js'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('changeItemAjax/', views.ChangeItemAjax, name='ChangeItemAjax'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('spec/', include('specifications.urls')),
    path('smartlombard/', include('smartlombardAPI.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('account/', include('account.urls')),
    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path
from . import views
from .views import CategoryDetailView2, ProductDetailView, SearchListView

app_name = 'shop'

urlpatterns = [
    path('search/', SearchListView.as_view(), name='search-list-view'),
    #
    path('', views.HomeListView.as_view(), name='StartPageViews'),
    # Список товаров
    path('category/<str:slug>/', CategoryDetailView2.as_view(), name='product_list_by_category'),
    #
    path('buying/', views.BuyingUp.as_view(), name='buying_up'),
    # Категории товаров
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    #
    path('<slug:category_slug>/<slug:product_slug>/', ProductDetailView.as_view(), name='product_detail'),
    # path('', views.HomeListView.as_view(), name='StartPageViews'),
    path('product-detail-spec-ajax/', views.ProductDetailSpecAjax, name='product-detail-spec-ajax'),
    #
    path('search-product-ajax/', views.SearchProductAjax, name='search-product-ajax'),
    #
    path('filter-ajax/', views.FilterAjax.as_view(), name='FilterAjax'),
]

shop/models.py
from django.db import models
from django.urls import reverse
import os
import uuid
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from PIL import Image
from django.core.validators import FileExtensionValidator


def image_folder(instance, filename):
    return 'photos/{}.webp'.format(uuid.uuid4().hex)


class Slider(models.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_image = self.image

    def save(self, *args, **kwargs):
        if self.image != self.__original_image:
            name = uuid.uuid4().hex
            image1 = Image.open(self.image)
            image1.save(f'media/slider/{name}.webp', 'WEBP')

            image2 = Image.open(self.image)
            image2.save(f'media/slider/{name}.jpeg', 'jpeg', quality=80)

            self.image = f'slider/{name}.webp'
            self.imageOLD = f'slider/{name}.jpeg'
        super(Slider, self).save(*args, **kwargs)

    name = models.CharField(max_length=100, verbose_name='Имя слайда')
    image = models.ImageField(verbose_name=_('Image'), upload_to='del/',)
    imageOLD = models.ImageField(verbose_name='JPG', upload_to='del/', blank=True)
    link_transition = models.URLField(verbose_name='Ссылка для перехода', blank=True, null=True)

    class Meta:
        verbose_name = 'Фотографии для слайдера'
        verbose_name_plural = '4. Фотографии слайдера'

    def __str__(self):
        return self.name


class Category(models.Model):
    def name_file(instance, filename):
        type_file = filename.split('.')[-1]
        return f'img_category/{instance.name}/{uuid.uuid4().hex}.{type_file}'

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to=name_file,
                              verbose_name="Изображение", blank=True)

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super().delete()

    def save(self, *args, **kwargs):
        if not self.image:
            self.image = 'img_default/no_image.jpg'
        super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = '2. Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    MONTH_CHOICES = (
        ("new", "Новый"),
        ("used", "б/у"),
    )

    condition = models.CharField(
        choices=MONTH_CHOICES, max_length=100, db_index=True, blank=False, verbose_name='состояние')

    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    name_spec = models.CharField(max_length=200, db_index=True, blank=True)
    url_spec = models.URLField(blank=True, null=True, verbose_name='URL на карточку товара')
    uploading_csv_file = models.FileField(upload_to='uploads/', blank=True, null=True,
                                          verbose_name='Вложение с характеристиками (CSV)',
                                          validators=[FileExtensionValidator(['csv'])])
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='цена')
    available = models.BooleanField(default=True, verbose_name='доступность')
    sold = models.BooleanField(default=False, verbose_name='продан')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id_crm = models.CharField(max_length=10, verbose_name='id продукта в CRM', blank=True, null=True)
    storage = models.IntegerField(default=1, verbose_name='Остатки')

    class Meta:
        ordering = ('-id',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = '1. Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.slug, self.slug])


class ProductImage(models.Model):
    def name_file(instance, filename):
        category = instance.product.category.slug
        name_product = instance.product.slug
        _path = f'product_photos/{category}/{name_product}/{filename}'
        return _path

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    image = models.ImageField(upload_to=name_file, verbose_name="Изображение", null=True, max_length=250)
    imageOLD = models.ImageField(upload_to=name_file, verbose_name='Изображение jpg',
                                 blank=True, null=True, max_length=250)
    is_main = models.BooleanField(default=False, verbose_name="Главное изображение")
    name = models.CharField(max_length=200, db_index=True, default=uuid.uuid4(), verbose_name="Имя")
    compression = models.BooleanField(default=False, verbose_name="Сжатие фотографии")
    # unique=True

    def __str__(self):
        return "%s" % self.pk

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = '3. Фотографии товаров'

shop/views.py
import json
from multiprocessing.sharedctypes import Value
from django.core.cache import cache
from django.http import HttpResponse, JsonResponse
from account.models import FavoriteProduct
from specifications.models import CharacteristicValue
from .models import Category, Product, Slider
from cart.forms import CartAddProductForm
from django.views.generic import DetailView, ListView, TemplateView, View
from django.db.models import Q
from django.db.models import Max, Min
from django.db import connection
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Count
from .modules.sterilization_of_products import *


class FilterAjax(View):
    def get(request, _p):
        _get = _p.GET.get('cat')
        _get = _get[0:-1].split('/')[-1]

        _vl = ('name_spec', 'id',)
        product = Product.objects.filter(category__slug=_get, available=True).exclude(name_spec='').values_list(*_vl)

        # кеш
        resultMinMax_cache = cache.get('resultMinMax_cache')
        if not resultMinMax_cache:
            resultMinMax_cache = Product.objects.aggregate(Min("price"), Max("price"))
            cache.set('resultMinMax_cache', resultMinMax_cache, 500)
        resultMinMax = resultMinMax_cache

        new_set_product = []
        p_min, p_max = resultMinMax['price__min'], resultMinMax['price__max']
        new_set_product.append(('price_min_max', f'{p_min}-{p_max}', 0.1))
        new_set_product.append(('Состояние', 'Новый', 0.2))
        new_set_product.append(('Состояние', 'Бывший в употреблении', 0.3))

        name_cache = "".join(map(lambda _i: str(_i[1]), product))
        product = list(map(lambda _i: _i[0], product))

        # кеш
        _q_cache = cache.get(name_cache)
        if not _q_cache:
            _q_cache = CharacteristicValue.objects.filter(
                name_product__name__in=product,
                name_spec__participation_filtering=True)
            _q_cache = _q_cache.values_list('name_spec__name', 'name_value__name', 'name_spec__priority_spec')
            cache.set(name_cache, _q_cache, 500)
        _q = _q_cache

        # _q = CharacteristicValue.objects.filter(name_product__name__in=product, name_spec__participation_filtering=True)
        # _q = _q.values_list('name_spec__name', 'name_value__name', 'name_spec__priority_spec')

        _q = list(_q)
        _q = _q + new_set_product
        status = {"status": _q}
        return JsonResponse(status, safe=True)


class CategoryDetailView2(ListView):
    model = Product
    context_object_name = 'category_products'
    template_name = 'shop/product_list/product_list.html'
    slug_url_kwarg = 'slug'
    paginate_by = 12

    @ staticmethod
    def find_get(f, url_kwargs):
        """Поиск товара по get запросу"""
        dict_spec_test = {}
        for i in f:
            for key, value in url_kwargs.items():
                if i.name_spec.name == key:
                    if i.name_value.name in value:
                        if not dict_spec_test.get(i.name_product):
                            dict_spec_test[i.name_product] = 0

                        c = dict_spec_test[i.name_product] + 1
                        dict_spec_test[i.name_product] = c
        return dict_spec_test.keys()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # кеш
        cat_cache = cache.get(self.kwargs['slug'])
        if not cat_cache:
            cat_cache = Category.objects.get(slug=self.kwargs.get(self.slug_url_kwarg, None))
            cache.set(self.kwargs['slug'], cat_cache, 500)

        context['categories'] = cat_cache

        cart_product_form = CartAddProductForm()
        context['cart_product_form'] = cart_product_form
        return context

    def get_queryset(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        price_min, price_max, condition, _sort = 0, 0, 0, ''
        dict_get = dict(self.request.GET)

        if dict_get.get('page'):
            dict_get.pop('page')

        if dict_get.get('priceMin'):
            price_min = dict_get['priceMin'][0]
            dict_get.pop('priceMin')

        if dict_get.get('priceMax'):
            price_max = dict_get['priceMax'][0]
            dict_get.pop('priceMax')

        if dict_get.get('sort'):
            _sort = dict_get['sort'][0]
            dict_get.pop('sort')

        _condition = []
        if dict_get.get('Состояние'):
            condition = dict_get['Состояние']
            if 'Бывший в употреблении' in condition:
                _condition.append('used')
            if 'Новый' in condition:
                _condition.append('new')

            dict_get.pop('Состояние')

        if dict_get:
            _p_all = Product.objects.exclude(name_spec__in=['', '0']).filter(category__slug=slug, available=True)
            if price_min and price_max:
                _p_all = _p_all.filter(price__gte=price_min, price__lte=price_max)

            if _condition:
                _p_all = _p_all.filter(condition__in=_condition)

            all_product = _p_all.values_list('name_spec')

            result = []
            for _i in dict_get.values():
                result.extend(_i)

            _q1 = Q(name_product__name__in=all_product)
            _q2 = Q(name_value__name__in=result)
            _values_list = ('name_product__name', 'name_spec__name', 'name_value__name')
            _r = CharacteristicValue.objects.filter(_q1, _q2).values_list(*_values_list)

            dict_test = {}
            for spec, value in dict_get.items():
                for item in _r:
                    if spec in item:
                        if dict_test.get(item[0]):
                            dict_test[item[0]] += 1
                        else:
                            dict_test[item[0]] = 1

            _yes = len(dict_get.keys())

            all_product = list(filter(lambda _i: dict_test[_i] == _yes, dict_test))

            if not all_product:
                # По заданным фильтрам ничего не найдено, выходм из функции!
                return all_product

            # Формируем запрос в базу данных
            _q = Product.objects.filter(name_spec__in=all_product, available=True)
            if _sort == 'price_low':
                _q = _q.order_by('price')
            elif _sort == 'price_high':
                _q = _q.order_by('-price')

            queryset = _q.select_related('category').prefetch_related('productimage_set')
        else:
            all_product = []

        if not all_product:
            _q = Product.objects.filter(category__slug=slug, available=True)
            if price_min and price_max:
                _q = _q.filter(price__gte=price_min, price__lte=price_max)
            if _condition:
                _q = _q.filter(condition__in=_condition)
            if _sort == 'price_low':
                _q = _q.order_by('price')
            elif _sort == 'price_high':
                _q = _q.order_by('-price')
            queryset = _q.select_related('category').prefetch_related('productimage_set')

        queryset = sterilization_of_products(queryset)

        return queryset


class ProductDetailView(DetailView):
    model = Product  # Модель шаблона
    template_name = 'shop/product_detail/product_detail.html'  # Путь и имя шаблона
    context_object_name = 'product'  # Какое имя необходимо отображать в шаблоне?
    # slug_field = 'slug' # Как называется slug в шаблоне?
    slug_url_kwarg = 'product_slug'  # Какое имя(slug) искать в url?

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cart_product_form = CartAddProductForm()
        context['cart_product_form'] = cart_product_form

        se_re = ('name_value', 'name_spec', 'name_product')
        f = CharacteristicValue.objects.filter(name_product__name=context['object'].name_spec).select_related(*se_re)
        context['spec_wi'] = f
        for i in f:
            if str(i.name_spec).find('Бренд') >= 0:
                context['brand_cast'] = i.name_value
                context['url_cast'] = f"/category/{self.kwargs['category_slug']}/?Бренд={i.name_value}"
                break

        # Избранные товары
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        product = Product.objects.filter(slug=slug, available=True)
        favorit = FavoriteProduct.objects.filter(id_product=product[0].pk)
        context['favorit'] = favorit

        return context

    def get_queryset(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg, None)
        queryset = Product.objects.filter(slug=slug, available=True)
        queryset = queryset.select_related('category').prefetch_related('productimage_set')
        # queryset = sterilization_of_products(queryset)
        return queryset


class HomeListView(ListView):
    model = Product
    template_name = 'shop/home_page/home_page.html'
    context_object_name = 'products'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        q_slider = Slider.objects.all()
        context['slider_photo'] = q_slider
        return context

    def get_queryset(self):
        queryset = Product.objects.select_related('category').prefetch_related('productimage_set')
        queryset = queryset.filter(available=True)[0:20]
        return sterilization_of_products(queryset)


class BuyingUp(TemplateView):
    template_name = 'shop/buying_up/buying_up.html'


class CategoryListView(ListView):
    model = Category
    template_name = 'shop/product_category/category.html'
    context_object_name = 'categories'

    def get_queryset(self):
        return Category.objects.annotate(cnt=Count('products')).filter(cnt__gt=0, products__available=True)


@ csrf_exempt
def ProductDetailSpecAjax(request):
    product_name = request.GET.get('product')

    product_name = Product.objects.filter(name=product_name).values('name_spec')

    if product_name:

shop/templates/shop/search/product_list.html
{% extends "shop/base_shop.html" %}

{% load static %}
{% load search_filter %}

{% block productfilter %}
{% endblock productfilter %}


{% block content %}
<main class="main">
    <!--  -->
    <div class="list-product container">
        <div class="list-product__header header-block">
            <span class="header-block__text">{{ categories }}</span>
        </div>
        <!--  -->
        <div class="list-product__wrapper">
            <!--  -->
            {% include 'shop/product_list/include/filters_ajax.html' %}
            <!--  -->
            <div class="list-product__background" data-removeattr="active>list-product__filters"
                data-removeattr2="look>body">
            </div>
            <!--  -->
            <div class="list-product__content">
                <!--  -->
                <div class="list-product__menu-sort product-menu-sort">
                    <div class="product-menu-sort__menu">
                        <div class="product-menu-sort__text">Сортировать по:</div>

                        <div class="product-menu-sort__select">
                            <select name="select">
                                <option value="price_d" selected>По умолчанию</option>
                                <option value="price_low">Дешевле</option>
                                <option value="price_high">Дороже</option>
                            </select>
                        </div>
                    </div>
                    <div class="product-menu-sort__listing-option dev_alert">
                        <span class="icon-listing-option-1"></span>
                        <span class="icon-listing-option-2 _active" data-addclass="active>list-product__content"></span>
                        <a class="product-menu-sort__btn-filter" data-addclass="active>list-product__filters"
                            data-addclass2="look>body" href="">
                            Фильтр
                        </a>
                    </div>
                </div>
                <!--  -->
                <div class="list-product__list-wrapper">
                    {% if not category_products %}
                    <div style='padding: 0 10px;'>
                        Похоже что по вашему запросу ничего не найдено, попробуйте изменить фильтры
                    </div>
                    {% endif %}

                    {% for product in category_products %}
                    <div class="list-product__item">
                        <div class="product-card">
                            <div class="product-card__img">
                                {% for prw in product.productimage_set.all %}
                                {% if prw.is_main %}
                                <a href="{{ product.get_absolute_url }}">
                                    <picture>
                                        <source type="image/webp" srcset="{{prw.image.url}}">
                                        {% if prw.imageOLD %}
                                        <img src="{{ prw.imageOLD.url }}">
                                        {% else %}
                                        <img src="">
                                        {% endif %}
                                    </picture>
                                </a>
                                {% endif %}
                                {% endfor %}
                            </div>
                            <div class="product-card__name">
                                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
                            </div>
                            <div class="product-card__price-inner">
                                <div class="product-card__price">{{ product.price }}<span class="rub"></span>.</div>
                                <div class="product-card__inner-icon">
                                    <div class="product-card__compare">
                                        <span class="icon-compare dev_alert"></span>
                                    </div>
                                    <div class="product-card__favourites">
                                        <span class="icon-favourites icon--hover"
                                            data-id-product='{{product.id}}'></span>
                                    </div>
                                </div>
                            </div>

                            <a href="{% url 'cart:cart_add_js' product.id %}" class="product-card__buttom btn-cart">В
                                корзину</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% include 'shop/product_list/include/_pagination.html' %}
            </div>
            <!--  -->
        </div>
        <!--  -->
    </div>
    <!--  -->
</main>
{% endblock content %}


{% block java_script %}
<script src="{% static 'libs/noUiSlider/nouislider.min.js' %}"></script>
<script src="{% static 'libs/noUiSlider/run-noUiSlider.js' %}"></script>
<script src="{% static 'js/click-add-class.js' %}"></script>
<script src="{% static '/js/click-remove-attr.js' %}"></script>
<script src="{% static '/js/render_filter.js' %}"></script>
<script src="{% static '/js/sorting_products.js' %}"></script>
<script src="{% static '/js/search_redefining_form.js' %}"></script>


{% endblock %}