cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('add_js/<int:product_id>/', views.cart_add_js, name='cart_add_js'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('changeItemAjax/', views.ChangeItemAjax, name='ChangeItemAjax'),
]

myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('spec/', include('specifications.urls')),
    path('smartlombard/', include('smartlombardAPI.urls')),
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('account/', include('account.urls')),
    path('shop_api/', include('shop_api.urls', namespace='shop_api')),
    path('', include('shop.urls', namespace='shop')),

]
if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [path('__debug__/', include(debug_toolbar.urls)), ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
]

shop/models.py
from django.db import models
from django.urls import reverse
import os
import uuid
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from PIL import Image
from django.core.validators import FileExtensionValidator


def image_folder(instance, filename):
    return 'photos/{}.webp'.format(uuid.uuid4().hex)


class Slider(models.Model):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.__original_image = self.image

    def save(self, *args, **kwargs):
        if self.image != self.__original_image:
            name = uuid.uuid4().hex
            image1 = Image.open(self.image)
            image1.save(f'media/slider/{name}.webp', 'WEBP')

            image2 = Image.open(self.image)
            image2.save(f'media/slider/{name}.jpeg', 'jpeg', quality=80)

            self.image = f'slider/{name}.webp'
            self.imageOLD = f'slider/{name}.jpeg'
        super(Slider, self).save(*args, **kwargs)

    name = models.CharField(max_length=100, verbose_name='Имя слайда')
    image = models.ImageField(verbose_name=_('Image'), upload_to='del/',)
    imageOLD = models.ImageField(verbose_name='JPG', upload_to='del/', blank=True)
    link_transition = models.URLField(verbose_name='Ссылка для перехода', blank=True, null=True)

    class Meta:
        verbose_name = 'Фотографии для слайдера'
        verbose_name_plural = '4. Фотографии слайдера'

    def __str__(self):
        return self.name


class Category(models.Model):
    def name_file(instance, filename):
        type_file = filename.split('.')[-1]
        return f'img_category/{instance.name}/{uuid.uuid4().hex}.{type_file}'

    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    image = models.ImageField(upload_to=name_file,
                              verbose_name="Изображение", blank=True)

    def delete(self, using=None, keep_parents=False):
        self.image.delete()
        super().delete()

    def save(self, *args, **kwargs):
        if not self.image:
            self.image = 'img_default/no_image.jpg'
        super(Category, self).save(*args, **kwargs)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = '2. Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    MONTH_CHOICES = (
        ("new", "Новый"),
        ("used", "б/у"),
    )

    condition = models.CharField(
        choices=MONTH_CHOICES, max_length=100, db_index=True, blank=False, verbose_name='состояние')

    category = models.ForeignKey(Category, related_name='products', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    name_spec = models.CharField(max_length=200, db_index=True, blank=True)
    url_spec = models.URLField(blank=True, null=True, verbose_name='URL на карточку товара')
    uploading_csv_file = models.FileField(upload_to='uploads/', blank=True, null=True,
                                          verbose_name='Вложение с характеристиками (CSV)',
                                          validators=[FileExtensionValidator(['csv'])])
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=0, verbose_name='цена')
    available = models.BooleanField(default=True, verbose_name='доступность')
    sold = models.BooleanField(default=False, verbose_name='продан')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    id_crm = models.CharField(max_length=10, verbose_name='id продукта в CRM', blank=True, null=True)
    storage = models.IntegerField(default=1, verbose_name='Остатки')

    class Meta:
        ordering = ('-id',)
        index_together = (('id', 'slug'),)
        verbose_name = 'Товар'
        verbose_name_plural = '1. Товары'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.category.slug, self.slug])


class ProductImage(models.Model):
    def name_file(instance, filename):
        category = instance.product.category.slug
        name_product = instance.product.slug
        _path = f'product_photos/{category}/{name_product}/{filename}'
        return _path

    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="Продукт")
    image = models.ImageField(upload_to=name_file, verbose_name="Изображение", null=True, max_length=250)
    imageOLD = models.ImageField(upload_to=name_file, verbose_name='Изображение jpg',
                                 blank=True, null=True, max_length=250)
    is_main = models.BooleanField(default=False, verbose_name="Главное изображение")
    name = models.CharField(max_length=200, db_index=True, default=uuid.uuid4(), verbose_name="Имя")
    compression = models.BooleanField(default=False, verbose_name="Сжатие фотографии")
    # unique=True

    def __str__(self):
        return "%s" % self.pk

    class Meta:
        verbose_name = 'Фотографию'
        verbose_name_plural = '3. Фотографии товаров'

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 4)]


class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(label='Количество', widget=forms.TextInput(
        attrs={'class': 'quantity-pr__input', 'value': '1', 'readonly': ''}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)


# name = forms.CharField()

cart/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from cart.forms import CartAddProductForm


# @require_POST  # Декоратор позволяет представлению обрабатывать только POST-запросы.
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)

    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_add_js(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.add(product=product)
    context = {'total': len(cart)}
    # return HttpResponse(status=201)
    return JsonResponse(context)


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'update': True})
    return render(request, 'cart/cart/cart.html', {'cart': cart})


def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()
    tempates = 'shop/product/detail.html'
    context = {'product': product, 'cart_product_form': cart_product_form}
    return render(request, tempates, context)


def ChangeItemAjax(request):
    product_id = request.GET.get('product_id')
    change = request.GET.get('item')
    cart = Cart(request)

    if change == 'add':
        cart.changeAdd(product_id)
    elif change == 'reduce':
        cart.changeReduce(product_id)

    total_price = cart.get_total_price()
    total_price_item = cart.get_total_price_item(product_id)
    cart_item = len(cart)

    context = {'total_price': total_price, 'total_price_item': total_price_item, 'cart_item': cart_item}
    # print(request.GET.get('product_id'))
    # return HttpResponse(status=200)
    return JsonResponse(context)

cart/templates/cart/cart/cart.html
{% extends "cart/base_cart.html" %}
{% load photo %}
{% block content %}
<main class="main">
    <!--  -->
    <div class="cart container">
        <!--  -->
        <div class="cart__header header-block">
            <span class="header-block__text">Корзина</span>
        </div>
        <!--  -->
        <div class="cart__content">
            <div class="cart__products products-cart">
                <!--  -->
                {% for item in cart %}
                {% with product=item.product %}
                <div class="products-cart__item">
                    <div class="products-cart__product">
                        {% for prw in product.productimage_set.all %}
                        {% if prw.is_main %}
                        <div class="products-cart__image">
                            {% picture_tag prw.image prw.imageOLD %}
                        </div>
                        {% endif %}
                        {% empty %}
                        <div class="products-cart__image">
                            {% picture_tag prw.image prw.imageOLD %}
                        </div>
                        {% endfor %}
                        <div class="products-cart__inner">
                            <div class="products-cart__name">{{ product.name }}</div>
                            <div class="products-cart__icon-wrapper">
                                <div class="products-cart__icon-favourites">
                                    <span class="icon-favourites icon--hover" data-id-product='{{product.id}}'></span>
                                </div>
                                <div class="products-cart__icon-trash-can">
                                    <a href="{% url 'cart:cart_remove' product.id%}">
                                        <span class="icon-trash-can icon--hover"></span>
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!--  -->
                    <div class="products-cart__price">
                        <div class="products-cart__quantity quantity-pr" data-quantity='{{product.id}}'>
                            <div class="quantity-pr__minus" data-q="-"><span>-</span></div>
                            {{ item.update_quantity_form.quantity }}
                            {% comment %} <input type="number" class="quantity-pr__input" value="1" /> {% endcomment %}
                            <div class="quantity-pr__plus" data-q="+"><span>+</span></div>
                        </div>
                        <div class="products-cart__total-price">
                            <span>{{ item.total_price }}</span>
                            <span class="rub"></span>
                        </div>
                    </div>
                </div>
                <!--  -->
                {% endwith %}
                {% endfor %}
                <!--  -->
            </div>
            <div class="cart__total-cost total-cost-cart">
                <div class="total-cost-cart__row">
                    <div class="total-cost-cart__text">
                        <span>В корзине 1 товар</span>
                    </div>
                    <div class="total-cost-cart__line"></div>
                    <div class="total-cost-cart__price">
                        <p>{{ cart.get_total_price }}</p>
                        <span class="rub"></span>
                    </div>
                </div>
                <div class="total-cost-cart__btn">
                    <a href='{% url 'orders:order_create' %}' class="btn-yellow">Перейти к оформлению</a>
                </div>
            </div>
        </div>
        <!--  -->
    </div>
    <!--  -->
</main>
{% endblock %}